// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: PageOasis

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Expand_Animation( lv_obj_t *TargetObject, int delay);
void Collapse_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
lv_obj_t *ui_Main_Screen;
void ui_event_Expand( lv_event_t * e);
lv_obj_t *ui_Expand;
lv_obj_t *ui_Lists_Bar;
lv_obj_t *ui_Button_Bar;
void ui_event_Collapse( lv_event_t * e);
lv_obj_t *ui_Collapse;
lv_obj_t *ui_Settings;
void ui_event_LightDarkToggle( lv_event_t * e);
lv_obj_t *ui_LightDarkToggle;
void ui_event_GridListToggle( lv_event_t * e);
lv_obj_t *ui_GridListToggle;
lv_obj_t *ui_Lists_Title_Bar;
lv_obj_t *ui_List_Title;
lv_obj_t *ui_Sort_Lists;
lv_obj_t *ui_PageOasisLogo;


// SCREEN: ui_Main_Screen1
void ui_Main_Screen1_screen_init(void);
lv_obj_t *ui_Main_Screen1;
void ui_event_Expand1( lv_event_t * e);
lv_obj_t *ui_Expand1;
lv_obj_t *ui_Lists_Bar1;
lv_obj_t *ui_Button_Bar1;
void ui_event_Collapse1( lv_event_t * e);
lv_obj_t *ui_Collapse1;
lv_obj_t *ui_Settings1;
void ui_event_LightDarkToggle1( lv_event_t * e);
lv_obj_t *ui_LightDarkToggle1;
void ui_event_GridListToggle1( lv_event_t * e);
lv_obj_t *ui_GridListToggle1;
lv_obj_t *ui_Lists_Title_Bar1;
lv_obj_t *ui_List_Title1;
lv_obj_t *ui_Sort_Lists1;
lv_obj_t *ui_PageOasisLogo1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Expand_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width );
lv_anim_set_values(&PropertyAnimation_0, 0, 250 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_width );
lv_anim_start(&PropertyAnimation_0);

}
void Collapse_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width );
lv_anim_set_values(&PropertyAnimation_0, 0, -250 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_width );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Expand( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Expand_Animation(ui_Lists_Bar, 0);
}
}
void ui_event_Collapse( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Collapse_Animation(ui_Lists_Bar, 0);
}
}
void ui_event_LightDarkToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Main_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_Screen1_screen_init);
      _ui_state_modify( ui_LightDarkToggle, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_GridListToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_GridListToggle1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
}
void ui_event_Expand1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Expand_Animation(ui_Lists_Bar1, 0);
}
}
void ui_event_Collapse1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Collapse_Animation(ui_Lists_Bar1, 0);
}
}
void ui_event_LightDarkToggle1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_Screen_screen_init);
      _ui_state_modify( ui_LightDarkToggle1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
}
void ui_event_GridListToggle1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_GridListToggle, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_Screen_screen_init();
ui_Main_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Main_Screen);
}
