// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: PageOasis

#ifndef _PAGEOASIS_UI_H
#define _PAGEOASIS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void Expand_Animation( lv_obj_t *TargetObject, int delay);
void Collapse_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
extern lv_obj_t *ui_Main_Screen;
void ui_event_Expand( lv_event_t * e);
extern lv_obj_t *ui_Expand;
extern lv_obj_t *ui_Lists_Bar;
extern lv_obj_t *ui_Button_Bar;
void ui_event_Collapse( lv_event_t * e);
extern lv_obj_t *ui_Collapse;
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_LightDarkToggle;
extern lv_obj_t *ui_GridListToggle;
extern lv_obj_t *ui_SortToggle;
extern lv_obj_t *ui_Lists_Title_Bar;
extern lv_obj_t *ui_List_Title;
extern lv_obj_t *ui_PageOasisLogo;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_467871261);   // assets\expand-sidebar-25px.png
LV_IMG_DECLARE( ui_img_1931740894);   // assets\Collapse-sidebar-25px.png
LV_IMG_DECLARE( ui_img_setting_icon_25px_png);   // assets\Setting_Icon_25px.png
LV_IMG_DECLARE( ui_img_grid_view_25px_png);   // assets\grid_view_25px.png
LV_IMG_DECLARE( ui_img_list_view_25px_png);   // assets\list_view_25px.png
LV_IMG_DECLARE( ui_img_1121264212);   // assets\A-Z_25px.png
LV_IMG_DECLARE( ui_img_1508908300);   // assets\Z-A_25px.png
LV_IMG_DECLARE( ui_img_pageoasislogo_png);   // assets\PageOasisLogo.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
